name: Test
on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        go: [1.12, 1.14]
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - run: go mod download
      - run: cd codegen/config && go test -v
